config/routes.rb
OatDogClub::Application.routes.draw do

  root 'static_pages#home'

  resources :users
  resources :zines
  resources :images, only: [:create, :show, :update]
  resources :paragraphs, only: [:create]
  resources :sessions, only: [:new, :create, :destroy]
  resources :authorships
  resources :zine_contents
  resources :covers, only: [:create, :update]

  match '/help',                                to: 'static_pages#help',                      via: 'get'
  match '/about',                               to: 'static_pages#about',                     via: 'get'
  match '/contact',                             to: 'static_pages#contact',                   via: 'get'
  match '/signup',                              to: 'users#new',                              via: 'get'
  match '/signin',                              to: 'sessions#new',                           via: 'get'
  match '/signout',                             to: 'sessions#destroy',                       via: 'delete'
  match '/zines/:id/publish-unpublish',         to: 'zines#publish',                          via: 'get'
  match '/paragraphs/:id/font-size',            to: 'paragraphs#font_size',                   via: 'get'
  match '/paragraphs/:id/delete',               to: 'paragraphs#destroy',                     via: 'get'
  match '/images/:id/delete',                   to: 'images#destroy',                         via: 'get'
  match '/zines/:id/title',                     to: 'zines#title',                            via: 'get'
  match '/zines/:id/authors',                   to: 'zines#authors',                          via: 'get'
  match '/zines/:id/:author/remove',            to: 'zines#remove_author',                    via: 'get'
  match '/zines/:id/',                          to: 'zines#add_author',                       via: 'post'
  match '/zines/:id/delete',                    to: 'zines#delete',                          via: 'get'
  match '/zinecontents/:id/position',           to: 'zine_contents#position',                 via: 'get'
  match '/covers/:id/remove',                   to: 'covers#remove',                          via: 'get'
  match '/covers/:id/make-cover',               to: 'covers#cover',                           via: 'get'
  match '/zinecontents/:id/hide-border-color',  to: 'zine_contents#hide_border_color',        via: 'get'

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>

      <li><%= link_to "Contact", contact_path, class: "btn btn-small btn-primary" %></li>
      <% if false %>
      <li><%= link_to "Help",    help_path, class: "btn btn-small btn-primary" %></li>
        <li><%= link_to "About",    about_path, class: "btn btn-small btn-primary" %></li>
        <% end %>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  
  <div class="container">
    <nav>

    <div class="nav navbar-nav navbar-left">
      <a href="/"><img class="oat-dog-logo" src="https://s3.amazonaws.com/oatdogclub/OatDogXS.png"></a><%= link_to "Oat Dog Club", root_path, class: "logo" %>
    </div>

      <ul class="nav navbar-nav navbar-right">
        <% if signed_in? %>
          <li class="new-zine-menu nav-li"><a href="#">New Zine!</a></li>
        <% end %>
          <li class="nav-li"><%= link_to "Zines", zines_path %></li>
          <li class="nav-li"><%= link_to "Members", users_path %></li>
        <% if signed_in? %>
          <li class="dropdown nav-li">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= current_user.try(:name) %>&nbsp;&nbsp;<span style="font-size: 75%;" class="glyphicon glyphicon-menu-hamburger" aria-hidden="true"></span>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Edit Membership", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Sign out", signout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li class="nav-li"><%= link_to "Sign up!", signup_path %></li>
          <li class="nav-li"><%= link_to "Sign in", signin_path %></li>
        <% end %>

      </ul>
      
    </nav>
  </div>

</header>

<div>
  <header class="phone-navbar navbar-fixed-top">
    
    <div class="container">
      <nav>

      <a href="/"><img class="phone-oat-dog-logo" src="https://s3.amazonaws.com/oatdogclub/OatDog500.png"></a>
      <a href="/">
        <div class="phone-logo">
          Oat Dog Club
        </div>
      </a>
      <ul class="phone-nav-ul">

          <% if signed_in? %>

            <li class="dropdown phone-nav-li phone-dropdown" style="margin-top: -5px;">
              <a href="#">
                <%= current_user.try(:name) %>&nbsp;&nbsp;&nbsp;<span style="font-size: 75%; vertical-align: middle; margin-top: -5px;" class="glyphicon glyphicon-menu-hamburger" aria-hidden="true"></span>
              </a>
            </li>


          <% else %>

          <li class="phone-nav-li"><%= link_to "Sign in", signin_path %></li>
          <li class="phone-nav-li"><%= link_to "Sign up!", signup_path %></li>

          <li class="phone-nav-li"><%= link_to "Members", users_path %></li>

          <li class="phone-nav-li"><%= link_to "Zines", zines_path %></li>
            
            

          <% end %>

        </ul>

  </header>
  <% if signed_in? %>
    <div class="phone-dropdown-menu invisible">
      <ul>
        <li class="new-zine-menu"><a href="#">New Zine!</a></li>
        <li class=""><%= link_to "Zines", zines_path %></li>
        <li class=""><%= link_to "Members", users_path %></li>
        <%= link_to '<li class="phone-dropdown-nav">Profile</li>'.html_safe, current_user %>
        <%= link_to '<li class="phone-dropdown-nav">Edit Membership</li>'.html_safe, edit_user_path(current_user) %>
        <li class="divider phone-dropdown-nav"></li>
        <%= link_to '<li class="phone-dropdown-nav">Sign out</li>'.html_safe, signout_path, method: "delete"  %>

      </ul>
    </div>
    <div class="grayout invisible" %>
    </div>
    <% end %>
</div>


<%= render 'zines/new' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= favicon_link_tag 'favicon128.png', rel: 'apple-touch-icon', type: 'image/png' %>
  <%= render 'layouts/shim' %>
</head>
  <body style="background-image: url('https://s3.amazonaws.com/oatdogclub/oatpattern3.jpg')">
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="center alert alert-<%= key %>"><%= value %></div> 
      <% end %>

      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
    <%= javascript_include_tag "application" %>
  </body>
</html>